[package]
name = "seeklocal-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "seeklocal_desktop"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
seeklocal-core = { path = "../../../crates/seeklocal-core" }
serde.workspace = true
tauri = { version = "2.11.5", features = [] }
tauri-plugin-dialog = "2.7.3"
